config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :charges, only: [:new, :create]

  resources :topics

  resources :wikis


  get 'show' => 'users#show'
  get 'about' => 'welcome#about'
  get 'premium' => 'wikis#premium'
  get 'standard' => 'wikis#standard'


end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :integer
#  users_id   :integer
#

class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  #validations
  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 15}, presence: true


# Scopes

# Returns Public Wikis
  scope :public_wikis, -> { where(private: false) }
# Returns User's Wikis
  scope :personal_wikis, -> (user) { where(user: user) }
# Returns User's Collaborations
  scope :shared_wikis, -> (user) { joins(:collaborations).where({ collaborations: { user: user } }) }



end

app/controllers/wikis_controller.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :integer
#  users_id   :integer
#

class WikisController < ApplicationController
  before_filter :authenticate_user!


  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
    @collaborations = User.all - [current_user]
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @wiki.user = current_user
    @collaborations = User.all - [@wiki.user]
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Your Wiki has been created"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your Wiki, please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Your Wiki has been created"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your Wiki, please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.delete
      flash[:notice] = "Your Wiki has been deleted"
      redirect_to request.referrer
    else
      flash.now[:alert] = "We couldn't delete your wiki, please try again."
      redirect_to request.referrer
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, user_ids: [])
  end
end

app/helpers/wikis_helper.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :integer
#  users_id   :integer
#

module WikisHelper
end

app/views/wikis/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1> Wiki Form </h1>
      <p> Guidelines for Wikis </p>
      <ul>
        <li> Stay on topic </li>
        <li> Incorperate as many puns as possible </li>
        <li> Please, do not write anything your dog would be ashamed of </li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>

      <div class="form-group" >
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Wiki Title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Wiki Body' %>
      </div>

      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>

      <div class="form-group">
        <%= f.collection_check_boxes(:user_ids, @collaborations, :id, :name ) %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/wikis/edit.html.erb
<%= render partial: 'form', locals: {wiki: @wiki} %>

app/views/wikis/index.html.erb
<div class="container">
  <h1>All Wikis</h1>

  <div class="row">
    <div class="col-md-8">
      <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
      <% end %>

    </div>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1> Wiki Form </h1>
      <p> Guidelines for Wikis </p>
      <ul>
        <li> Stay on topic </li>
        <li> Incorperate as many puns as possible </li>
        <li> Write nothing your dog would be ashamed of </li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>
      <% if @wiki.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
        <ul>
          <% @wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-group" >
        <%= f.label :title %>

        <%= f.text_field :title, class: 'form-control', placeholder: "Wiki Title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Wiki Body' %>
      </div>

      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <h1><%= @wiki.title %></h1>
  <div class="row">
    <div class="col-md-8">
      <p><%= markdown(@wiki.body).html_safe %></p>
    </div>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
  </div>
</div>