config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :charges, only: [:new, :create]

  resources :topics

  resources :wikis


  get 'show' => 'users#show'
  get 'about' => 'welcome#about'
  get 'premium' => 'wikis#premium'
  get 'standard' => 'wikis#standard'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Nav Bar  -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <!-- Toggle Button -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Toggle Button End -->

      <%= link_to 'Blocipedia', root_path, class: "navbar-brand text-muted"  %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left" >
          <li><%= link_to "About", '#' %></li>

          <li class='dropdown'>
            <a data-toggle='dropdown' data-target='#'>Wikis<b class='caret'></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Wikis', wikis_path %></li>
            </ul>
          </li>

          <li class='dropdown'>
            <a data-toggle='dropdown' data-target='#'>Plans<b class='caret'></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Standard Plan', standard_path %></li>
              <li><%= link_to 'Premium Plan', premium_path %></li>
            </ul>
          </li>
        </ul>

        <ul class= "nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class='dropdown'>
            <a data-toggle='dropdown' data-target='#'><%= current_user.name %><b class='caret'></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Profile', show_path %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            </ul>
          </li>

          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %>

          <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
      <!-- Nav Bar End -->
    </div>
  </div>

  <div class="container">
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>




    <%= yield %>
  </div>
</body>
</html>